version: '3.8'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: api_sam
    ports:
      - "8000:8000"
    volumes:
      - .:/var/www/html
    networks:
      - laravel_network
    depends_on:
      - db
    working_dir: /var/www/html
    command: ["php", "artisan", "serve", "--host=0.0.0.0", "--port=8000"]

  db:
    image: postgres:latest
    container_name: postgres_db
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: admin123@
      POSTGRES_DB: db
    networks:
      - laravel_network
    volumes:
      - db_data:/var/lib/postgresql/data

  pgadmin:
    image: dpage/pgadmin4
    container_name: pgadmin
    ports:
      - "5050:80"
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@example.com
      PGADMIN_DEFAULT_PASSWORD: admin123@
    networks:
      - laravel_network
    depends_on:
      - db

networks:
  laravel_network:

volumes:
  db_data:
